name = "MySave"
uuid = "241e21c6-5910-48d8-a785-954ac79dda43"
authors = ["Ryuichi Okamoto <ryubee@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.63"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
